### ISSUE TITLE
Publishing user on network

### ISSUE THREAD

**Issue by nigecooper77** [streembit/streembitlib#5]
On the screen 'Publishing User info to the network', if the software does not respond - animation is cycling.
last line of Log files is 
{"level":"debug","message":"contact tzpardi populated from network and updated. address: 81.129.190.149. port: 8905. protocol: tcp","timestamp":"2016-07-06T14:39:32.593Z"}
{"level":"debug","message":"get_account_messages","timestamp":"2016-07-06T14:39:32.893Z"}

OS: Windows 10
nwjs-sdk-v0.15.1
Streembit: v1.0.8

**Comment by zsoltpardi** [comment]
The new version of Streembit should fix this issue.
